name: Generate Reports for Open edX Events & Filters Adoptions

on:
  workflow_dispatch:

jobs:
  generate-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Generate Reports
        run: |
          make reports TOKEN=${{ secrets.GH_FINE_GRAINED_PAT }}

      - name: Push Open edX Events & Filters Reports to GitHub Branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b reports
          git add scripts/results/
          git commit -m "chore: generate Open edX Events & Filters Reports"
          git push -f origin reports
